### PR TITLE
fix: skip canvas SSE fetch in chat shared page to eliminate spurious 103 error

### LINKED ISSUE #14115: [Bug]: The links shared through chatting cannot search for the content of the knowledge base and are often inaccurate; however, in the chatting on the editing page, the content of the knowledge base can be correctly searched.
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### RAGFlow workspace code commit ID

5ece2d8aa898237225d36d3e799a27f4aeea0273

### RAGFlow image version

v0.24.0-456-g52442c8eb

### Other environment information

```Markdown

```

### Actual behavior

In the chat window of the shared link, input "How many days of annual leave do I have?" and be prompted that no relevant information was found.  But  Through the chat window on the editing page, search for "How many days of annual leave do I have?" and be able to search for and reply to questions normally from the knowledge base.

### Expected behavior

By using the shared link, we can normally access and view the contents in the knowledge base.

### Steps to reproduce

```Markdown
1. First, configure relevant parameters such as the knowledge base on the chat page and save it.
2. Through the chat window on the editing page, search for "How many days of annual leave do I have?" and be able to search for and reply to questions normally from the knowledge base.
3. Share the link through the sharing button on the editing page.
http://localhost/chats/share?shared_id=9bfd476a37ad11f1abc4cfaf6202627d&from=chat&auth=6v2pnrC78EIlA7WpEEBPOKcdNrPHx5Q3&theme=light
4. In the chat window of the shared link, input "How many days of annual leave do I have?" and be prompted that no relevant information was found.

<img width="810" height="563" alt="Image" src="https://github.com/user-attachments/assets/7cf3b92c-df52-4ee1-899e-4885bad0afc5" />

<img width="947" height="195" alt="Image" src="https://github.com/user-attachments/assets/c524eda6-593f-420a-a109-243e63b9fe54" />
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by euvre**
## What does this PR do?

Fixes the `hint : 103 Only owner of canvas authorized for this operation` error that appears when opening a **Chat** shared link (`/chats/share?shared_id=...&from=chat`).

## Root Cause

The Chat shared page (`web/src/pages/next-chats/share/index.tsx`) unconditionally calls `useFetchFlowSSE()`, which requests `/api/canvas/getsse/{sharedId}`. This is an Agent Canvas endpoint that validates canvas ownership. When sharing a **Chat** dialog (not an Agent):

1. `sharedId` is a `dialog_id`, not a `canvas_id`
2. The API token's `tenant_id` doesn't match any canvas owner
3. The backend returns `code: 103, message: "Only owner of canvas authorized for this operation."`
4. The global error interceptor in `request.ts` displays it as a notification: `hint : 103 Only owner of canvas authorized for this operation.`

## Changes

- **`web/src/hooks/use-agent-request.ts`**: Added an `enabled` parameter to `useFetchFlowSSE` so callers can conditionally skip the query.
- **`web/src/pages/next-chats/share/index.tsx`**: Only enable `useFetchFlowSSE` when `from === SharedFrom.Agent`. For Chat shares, the hook is disabled, avoiding the unnecessary canvas API call entirely.

## Related Issue

Closes #14115

### Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by xugangqiang** [comment]
@euvre 
Could you please conduct regression tests and upload testing evidence?
Thanks.

File: web/src/pages/next-chats/share/index.tsx [hunk 1]
```diff
@@ -44,15 +44,16 @@ const ChatContainer = () => {
...
+  const { data: flowData } = useFetchFlowSSE(isAgent);
   React.useEffect(() => {
     if (locale && i18n.language !== locale) {
       changeLanguageAsync(locale);
     }
   }, [locale, visibleAvatar]);
 
   const avatarDialogSrc =
-    from === SharedFrom.Agent ? flowData?.avatar : chatInfo.avatar;
+    isAgent ? flowData?.avatar : chatInfo.avatar;
```
Comment (cike8899) [inline web/src/pages/next-chats/share/index.tsx]: useFetchFlowSSE does not need to be called on the current page; the avatar is directly read from chatInfo.avatar.
